### ISSUE TITLE
Send USN Update dispatches to Jammy stack repos

### ISSUE THREAD

**Issue by fg-j** [paketo-buildpacks/stack-usns#600]
The Jammy Stacks [RFC](https://github.com/paketo-buildpacks/rfcs/blob/main/text/stacks/0004-jammy-jellyfish.md) has called for the creation of 3 new stacks repos (`paketo-buildpacks/jammy-full-stack`, `paketo-buildpacks/jammy-base-stack`, and `paketo-buildpacks/jammy-tiny-stack`). These repos will be responsible for running the automation that builds and releases each of the Jammy stacks. They should be set up to receive repo dispatches from this repo when there are new USNs.

**Comment by ryanmoran** [comment]
Should we consider pushing this logic out into each of the stack repos so that we don't have this complex of a setup for rebuilding on USN announcements?

**Comment by fg-j** [comment]
I'm open to that. I'm digging into how these updates currently work.

**Comment by fg-j** [comment]
This is no longer needed with the approach that's been taken in the Jammy stacks implementation.
